//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kip.Perk.API.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserClaim
    {
        public string ClaimId { get; set; }
        public string UserId { get; set; }
        public int TeamId { get; set; }
        public int PointsToClaim { get; set; }
        public Nullable<System.DateTime> ClaimDate { get; set; }
        public int Status { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DateOfVerification { get; set; }
        public string Description { get; set; }
    }
}
